# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='map_msg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmap_msg.proto\"X\n\x07\x44\x65moMap\x12 \n\x04map1\x18\x01 \x03(\x0b\x32\x12.DemoMap.Map1Entry\x1a+\n\tMap1Entry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\x08\x44\x65moData\x12\n\n\x02\x66\x31\x18\x01 \x01(\x05\x12\n\n\x02\x66\x32\x18\x02 \x01(\t\"e\n\x08\x44\x65mo2Map\x12!\n\x04map1\x18\x01 \x03(\x0b\x32\x13.Demo2Map.Map1Entry\x1a\x36\n\tMap1Entry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.DemoData:\x02\x38\x01\x62\x06proto3')
)




_DEMOMAP_MAP1ENTRY = _descriptor.Descriptor(
  name='Map1Entry',
  full_name='DemoMap.Map1Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DemoMap.Map1Entry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='DemoMap.Map1Entry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=105,
)

_DEMOMAP = _descriptor.Descriptor(
  name='DemoMap',
  full_name='DemoMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='map1', full_name='DemoMap.map1', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DEMOMAP_MAP1ENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=105,
)


_DEMODATA = _descriptor.Descriptor(
  name='DemoData',
  full_name='DemoData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f1', full_name='DemoData.f1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f2', full_name='DemoData.f2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=141,
)


_DEMO2MAP_MAP1ENTRY = _descriptor.Descriptor(
  name='Map1Entry',
  full_name='Demo2Map.Map1Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Demo2Map.Map1Entry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Demo2Map.Map1Entry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=244,
)

_DEMO2MAP = _descriptor.Descriptor(
  name='Demo2Map',
  full_name='Demo2Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='map1', full_name='Demo2Map.map1', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DEMO2MAP_MAP1ENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=244,
)

_DEMOMAP_MAP1ENTRY.containing_type = _DEMOMAP
_DEMOMAP.fields_by_name['map1'].message_type = _DEMOMAP_MAP1ENTRY
_DEMO2MAP_MAP1ENTRY.fields_by_name['value'].message_type = _DEMODATA
_DEMO2MAP_MAP1ENTRY.containing_type = _DEMO2MAP
_DEMO2MAP.fields_by_name['map1'].message_type = _DEMO2MAP_MAP1ENTRY
DESCRIPTOR.message_types_by_name['DemoMap'] = _DEMOMAP
DESCRIPTOR.message_types_by_name['DemoData'] = _DEMODATA
DESCRIPTOR.message_types_by_name['Demo2Map'] = _DEMO2MAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DemoMap = _reflection.GeneratedProtocolMessageType('DemoMap', (_message.Message,), dict(

  Map1Entry = _reflection.GeneratedProtocolMessageType('Map1Entry', (_message.Message,), dict(
    DESCRIPTOR = _DEMOMAP_MAP1ENTRY,
    __module__ = 'map_msg_pb2'
    # @@protoc_insertion_point(class_scope:DemoMap.Map1Entry)
    ))
  ,
  DESCRIPTOR = _DEMOMAP,
  __module__ = 'map_msg_pb2'
  # @@protoc_insertion_point(class_scope:DemoMap)
  ))
_sym_db.RegisterMessage(DemoMap)
_sym_db.RegisterMessage(DemoMap.Map1Entry)

DemoData = _reflection.GeneratedProtocolMessageType('DemoData', (_message.Message,), dict(
  DESCRIPTOR = _DEMODATA,
  __module__ = 'map_msg_pb2'
  # @@protoc_insertion_point(class_scope:DemoData)
  ))
_sym_db.RegisterMessage(DemoData)

Demo2Map = _reflection.GeneratedProtocolMessageType('Demo2Map', (_message.Message,), dict(

  Map1Entry = _reflection.GeneratedProtocolMessageType('Map1Entry', (_message.Message,), dict(
    DESCRIPTOR = _DEMO2MAP_MAP1ENTRY,
    __module__ = 'map_msg_pb2'
    # @@protoc_insertion_point(class_scope:Demo2Map.Map1Entry)
    ))
  ,
  DESCRIPTOR = _DEMO2MAP,
  __module__ = 'map_msg_pb2'
  # @@protoc_insertion_point(class_scope:Demo2Map)
  ))
_sym_db.RegisterMessage(Demo2Map)
_sym_db.RegisterMessage(Demo2Map.Map1Entry)


_DEMOMAP_MAP1ENTRY._options = None
_DEMO2MAP_MAP1ENTRY._options = None
# @@protoc_insertion_point(module_scope)
