# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: struct_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='struct_t.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0estruct_t.proto\x1a\x1cgoogle/protobuf/struct.proto\"3\n\nTestStruct\x12%\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Structb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_TESTSTRUCT = _descriptor.Descriptor(
  name='TestStruct',
  full_name='TestStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='TestStruct.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=99,
)

_TESTSTRUCT.fields_by_name['data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['TestStruct'] = _TESTSTRUCT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestStruct = _reflection.GeneratedProtocolMessageType('TestStruct', (_message.Message,), dict(
  DESCRIPTOR = _TESTSTRUCT,
  __module__ = 'struct_t_pb2'
  # @@protoc_insertion_point(class_scope:TestStruct)
  ))
_sym_db.RegisterMessage(TestStruct)


# @@protoc_insertion_point(module_scope)
